# Commonly-used INI preset file for run_celluniverse.sh
# Paths can be absolute or relative to this INI file's directory.

[default]
build_dir=../build
input_path=input
output_base_dir=.
output_name_rule=output_{preset}_{timestamp}
cell_config_file=config.yaml
initial_csv_file=initial.csv
cli_args_file=runauto.args
first_frame=1
last_frame=19

[original_data]
build_dir=../build
input_path=input/original_data/frame%03d.tif
output_base_dir=.
output_name_rule=output_{preset}_{timestamp}
cell_config_file=config.yaml
initial_csv_file=initial.csv
cli_args_file=runauto.args
first_frame=1
last_frame=19
