base_config: config_cell_lumen_embryo_early_v022_densityBandedFloor_zstrong_count20to30.yaml

cell_lumen:
  fragmentMergeSparseMinDistance: 24.0
  fragmentMergeSparseMajorScale: 1.70
  fragmentMergeModerateMinDistance: 18.0
  fragmentMergeModerateMajorScale: 1.35
