classDiagram

class Cell {
  +Cell()
  +~Cell()
  +draw(image, simulationConfig, cellMap, z)*
  +drawOutline(image, color, z)*
  +getPerturbedCell()*
  +getParameterizedCell(params)*
  +getSplitCells()*
  +getCellParams()*
  +checkIfCellsValid(cells)$
  +calculateCorners()*
  +calculateMinimumBox(perturbed_cell)*
}

class CellParams {
  +string name
  +CellParams(name)
}

class SphereParams {
  +float x
  +float y
  +float z
  +float radius
  +SphereParams()
  +SphereParams(name, x, y, z, radius)
}

class SpheroidParams {
  +float x
  +float y
  +float z
  +vector~float~ x_vec
  +vector~float~ y_vec
  +vector~float~ z_vec
  +float majorRadius
  +float minorRadius
  +float theta_x
  +float theta_y
  +float theta_z
  +SpheroidParams()
  +SpheroidParams(name, x, y, z, majorRadius, minorRadius)
  +SpheroidParams(name, x, y, z, majorRadius, minorRadius, theta_x, theta_y, theta_z)
  +SpheroidParams(name, x, y, z, x_vec, y_vec, z_vec)
  +parseParams(x, y, z, x_vec, y_vec, z_vec)
}

class Sphere {
  -string _name
  -Point3f _position
  -double _radius
  -double _rotation
  -bool dormant
  +SphereConfig cellConfig$
  +Sphere(init_props)
  +Sphere()
  +printCellInfo()
  +getRadiusAt(z)
  +draw(image, simulationConfig, cellMap, z)
  +drawOutline(image, color, z)
  +getPerturbedCell()
  +getParameterizedCell(params)
  +performPCA(pts, frame)
  +calculateContours(subTiffSlices, contours3D)$
  +getSplitCells(realTiffSlices)
  +checkConstraints()
  +getCellParams()
  +calculateCorners()
  +checkIfCellsValid(spheres)
  +calculateMinimumBox(perturbed_cell)
  +checkIfCellsOverlap(spheres)$
}

class Spheroid {
  -string _name
  -vector~double~ _x_vec
  -vector~double~ _y_vec
  -vector~double~ _z_vec
  -Point3f _position
  -double _major_radius
  -double _minor_radius
  -double _theta_x
  -double _theta_y
  -double _theta_z
  -bool dormant
  +SpheroidParams paramClass$
  +SpheroidConfig cellConfig$
  +Spheroid(init_props)
  +Spheroid()
  +printCellInfo()
  +getShapeAt(z)
  +draw(image, simulationConfig, cellMap, z)
  +drawOutline(image, color, z)
  +getPerturbedCell()
  +getParameterizedCell(params)
  +getSplitCells(image, z_scaling)
  +performPCA(points)
  +checkConstraints()
  +getCellParams()
  +calculateCorners()
  +checkIfCellsValid(spheroids)
  +calculateMinimumBox(perturbed_cell)
  +checkIfCellsOverlap(spheroids)$
  +major_magnitude()
  +minor_magnitude()
  +get_center()
  +print()
  +get_matrix_size()
  -inverseRotatePoint(dx, dy, dz, lx, ly, lz)
}

class Bacilli {
  +Bacilli(name, x, y, width, length, rotation, split_alpha, opacity)
  +_refresh()
  +draw(...)
  +draw_outline(image, color)
  +split(alpha)
  +combine(cell)
  +toString()
  +simulated_region()
  +getRegion()
  +getPosition()
  +getX()
  +setX(value)
  +getY()
  +setY(value)
  +getWidth()
  +setWidth(value)
}

class Vector {
  +double x
  +double y
  +double z
  +Vector()
  +Vector(x, y, z)
  +operator+(other)
  +operator+(val)
  +dotProduct(other)
}

class SimulationConfig {
  +int iterations_per_cell
  +float background_color
  +float cell_color
  +int padding
  +float z_scaling
  +float blur_sigma
  +int z_slices
  +vector~int~ z_values
  +SimulationConfig()
  +explodeConfig(node)
  +printConfig()
}

class ProbabilityConfig {
  +float perturbation
  +float split
  +float split_cost
  +ProbabilityConfig()
  +explodeConfig(node)
  +printConfig()
}

class PerturbParams {
  +float prob
  +float mu
  +float sigma
  +explodeParams(node)
  +getPerturbOffset()
}

class CellConfig {
  <<abstract>>
  +explodeConfig(node)*
  +~CellConfig()
}

class SphereConfig {
  +PerturbParams x
  +PerturbParams y
  +PerturbParams z
  +PerturbParams radius
  +double minRadius
  +double maxRadius
  +double boundingBoxScale
  +explodeConfig(node)
}

class SpheroidConfig {
  +PerturbParams x
  +PerturbParams y
  +PerturbParams z
  +PerturbParams majorRadius
  +PerturbParams minorRadius
  +PerturbParams thetaX
  +PerturbParams thetaY
  +PerturbParams thetaZ
  +double minMajorRadius
  +double maxMajorRadius
  +double minMinorRadius
  +double maxMinorRadius
  +explodeConfig(node)
}

class BaseConfig {
  +string cellType
  +SpheroidConfig* cell
  +SimulationConfig simulation
  +ProbabilityConfig prob
  +BaseConfig()
  +operator=(other)
  +BaseConfig(other)
  +~BaseConfig()
  +explodeConfig(node)
  +printConfig()
}

class CellFactory {
  +CellFactory(config)
  +createCells(init_params_path, z_offset, z_scaling)
}

class Frame {
  +vector~Spheroid~ cells
  +Frame(realFrame, simulationConfig, cells, outputPath, imageName)
  +padRealFrame()
  +generateSynthFrame()
  +generateSynthFrameFast(oldCell, newCell)
  +calculateCost(synthFrame)
  +generateOutputFrame()
  +generateOutputSynthFrame()
  +length()
  +perturb()
  +split()
  +trySplitCell(cellIndex)
  +gradientDescent()
  +getSynthFrame()
  +getImageName()
  -getImageShape()
  -costOfPerturb(perturbParam, perturbVal, index, oldCell)
  -getSynthPerturbedCells(index, params, perturbLength, oldCell)
}

class Lineage {
  +Lineage(initialCells, imagePaths, config, outputPath, continueFrom)
  +optimize(frameIndex)
  +saveImages(frameIndex)
  +saveCells(frameIndex)
  +copyCellsForward(to)
  +length()
}

class Args_main {
  <<src/main.cpp>>
  +string config
  +string input
  +int firstFrame
  +int lastFrame
  +string initial
  +string output
  +int continueFrom
}

class Args_cli {
  <<args.cpp>>
  +string input
  +path output
  +path config
  +path initial
  +optional~path~ debug
  +int first_frame
  +int last_frame
  +int workers
  +int jobs
  +string cluster
  +bool no_parallel
  +bool auto_temp
  +optional~float~ start_temp
  +optional~float~ end_temp
  +optional~path~ residual
  +int continue_from
  +optional~int~ seed
  +int batches
  +postInit()
}

class MainCppFunctions {
  <<utility>>
  +updateTiffConfigIfNeeded(file, config)
  +getImageFilePaths(input, firstFrame, lastFrame, config)
  +loadConfig(path, config)
  +main(argc, argv) : int
}

class LineageFunctions {
  <<utility>>
  +processImage(image, config)
  +loadFrame(imageFile, config)
}

class FrameFunctions {
  <<utility>>
  +interpolateSlices(slice1, slice2, processedSlices, numInterpolations)
}

class SpheroidCppFunctions {
  <<utility>>
  +_get_magnitude(vec)
}

class LineageUtils {
  <<utility>>
  +printMat~T~(mat)
}

class ArgsCppFunctions {
  <<utility>>
  +main(argc, argv) : int
}

CellParams <|-- SphereParams
CellParams <|-- SpheroidParams
CellConfig <|-- SphereConfig
CellConfig <|-- SpheroidConfig
Cell <|-- Bacilli

BaseConfig *-- SimulationConfig
BaseConfig *-- ProbabilityConfig
BaseConfig o-- SpheroidConfig
SphereConfig *-- PerturbParams
SpheroidConfig *-- PerturbParams

CellFactory --> BaseConfig
CellFactory --> Spheroid
Lineage *-- Frame
Lineage --> BaseConfig
Frame o-- Spheroid
Frame --> SimulationConfig
Sphere --> SphereConfig
Spheroid --> SpheroidConfig
Spheroid --> SpheroidParams
Sphere --> SphereParams
Bacilli --> Vector

MainCppFunctions --> Args_main
MainCppFunctions --> BaseConfig
MainCppFunctions --> CellFactory
MainCppFunctions --> Lineage
MainCppFunctions --> Spheroid
LineageFunctions --> BaseConfig
LineageFunctions --> Lineage
FrameFunctions --> Frame
SpheroidCppFunctions --> Spheroid
ArgsCppFunctions --> Args_cli
